using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace yalms.Models
{
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:37
   /// Object derived from the  Couser_Student table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    [Table("Couser_Student")]
    public class Couser_Student
    {
        [Key]
        public int Couser_StudentID { get; set; }

        [Required(ErrorMessage = "Field can not be empty.")]
        [Display(Name = "Course")]
        public int CourseID  { get; set; }

        [Required(ErrorMessage = "Field can not be empty.")]
        [Display(Name = "Student_User")]
        public int Student_UserID  { get; set; }


        // objects for sub key data relationship
        [NotMapped]
        public Course CourseID_Course { get; set; }
        [NotMapped]
        public User Student_UserID_Student_User { get; set; }



        #region DMZ - Custome Code placed in the DMZ will be protected from system overwrites.


        #endregion DMZ End

    }
}

