using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace yalms.Models
{
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:38
   /// Object derived from the  Slot table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    [Table("Slot")]
    public class Slot
    {
        [Key]
        public int SlotID { get; set; }

        [Display(Name = "Course")]
        public int? CourseID  { get; set; }

        [Display(Name = "Room")]
        public int? RoomID  { get; set; }

        [Display(Name = "SlotNR")]
        public int? SlotNR  { get; set; }

        [Display(Name = "WeekDay")]
        public int? WeekDay  { get; set; }

        [Display(Name = "WeekNR")]
        public int? WeekNR  { get; set; }


        // objects for sub key data relationship
        [NotMapped]
        public Course CourseID_Course { get; set; }
        [NotMapped]
        public Room RoomID_Room { get; set; }

        // System Objects.
        [NotMapped] 
        public User CreatedBy_User { get; set; }

        [NotMapped] 
        public User ModifiedBy_User { get; set; }

        [NotMapped] 
        public User RemovedBy_User { get; set; }

        #region DMZ - Custome Code placed in the DMZ will be protected from system overwrites.


        #endregion DMZ End

    }
}

