using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace yalms.Models
{
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:38
   /// Object derived from the  User table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    [Table("User")]
    public class User
    {
        [Key]
        public int UserID { get; set; }

        [Required(ErrorMessage = "Field can not be empty.")]
        [Display(Name = "FullName")]
        public string FullName  { get; set; }

        [Required(ErrorMessage = "Field can not be empty.")]
        [Display(Name = "PassWord")]
        public string PassWord  { get; set; }

        [Display(Name = "Title")]
        public string Title  { get; set; }

        [Required(ErrorMessage = "Field can not be empty.")]
        [Display(Name = "UserName")]
        public string UserName  { get; set; }

        [Required(ErrorMessage = "Field can not be empty.")]
        [Display(Name = "UserType")]
        public int UserTypeID  { get; set; }


        // objects for sub key data relationship

        // System Objects.
        [NotMapped] 
        public User CreatedBy_User { get; set; }

        [NotMapped] 
        public User ModifiedBy_User { get; set; }

        [NotMapped] 
        public User RemovedBy_User { get; set; }

        #region DMZ - Custome Code placed in the DMZ will be protected from system overwrites.


        #endregion DMZ End

    }
}

