using System; 
using System.Data; 
using System.Data.Entity; 
using System.Collections.Generic; 
using yalms.Models; 

namespace yalms.DAL 
{ 
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:37
   /// Object derived from the  Couser_Student table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    public interface ICouser_StudentRepository : IDisposable 
    { 

        IEnumerable<Couser_Student> GetAllCouser_Students(); 
        Couser_Student GetCouser_Student_SimpleByID(int? couser_StudentID); 
        Couser_Student GetCouser_StudentByID(int? couser_StudentID); 

        Couser_Student GetNewestCouser_Student(); 
        void InsertCouser_Student(Couser_Student company, int couser_StudentID); 
        void DeleteCouser_Student(int couser_StudentID); 
        void UpdateCouser_Student(Couser_Student company, int couser_StudentID); 
        void Save(); 


     } 
} 

