using System; 
using System.Data; 
using System.Data.Entity; 
using System.Collections.Generic; 
using yalms.Models;
using Microsoft.AspNet.Identity.EntityFramework; 

namespace yalms.DAL 
{ 
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:37
   /// Object derived from the  Course table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    public interface ICourseRepository : IDisposable 
    { 

        IEnumerable<Course> GetAllCourses(); 
        Course GetCourse_SimpleByID(int? courseID); 
        Course GetCourseByID(int? courseID); 

        Course GetNewestCourse();
        List<IdentityUser> ListAllStudentsTakingCourse();
        void InsertCourse(Course company, int courseID); 
        void DeleteCourse(int courseID); 
        void UpdateCourse(Course company, int courseID); 
        void Save(); 


     } 
} 

