using System; 
using System.Data; 
using System.Data.Entity; 
using System.Collections.Generic; 
using yalms.Models; 

namespace yalms.DAL 
{ 
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:37
   /// Object derived from the  Room table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    public interface IRoomRepository : IDisposable 
    { 
        IEnumerable<Room> GetAllRooms(); 
        Room GetRoom_SimpleByID(int? roomID); 
        Room GetRoomByID(int? roomID); 

        Room GetNewestRoom(); 
        void InsertRoom(Room company, int roomID); 
        void DeleteRoom(int roomID); 
        void UpdateRoom(Room company, int roomID); 
        void Save(); 


     } 
} 

