using System; 
using System.Data; 
using System.Data.Entity; 
using System.Collections.Generic; 
using yalms.Models; 

namespace yalms.DAL 
{ 
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:37
   /// Object derived from the  SchoolClass table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    public interface ISchoolClassRepository : IDisposable 
    { 
        IEnumerable<SchoolClass> GetAllSchoolClasses(); 
        SchoolClass GetSchoolClass_SimpleByID(int? schoolClassID); 
        SchoolClass GetSchoolClassByID(int? schoolClassID); 

        SchoolClass GetNewestSchoolClass(); 
        void InsertSchoolClass(SchoolClass company, int schoolClassID); 
        void DeleteSchoolClass(int schoolClassID); 
        void UpdateSchoolClass(SchoolClass company, int schoolClassID); 
        void Save(); 


     } 
} 

