using System; 
using System.Data; 
using System.Data.Entity; 
using System.Collections.Generic; 
using yalms.Models; 

namespace yalms.DAL 
{ 
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:38
   /// Object derived from the  SchoolClassStudent table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    public interface ISchoolClassStudentRepository : IDisposable 
    { 
        IEnumerable<SchoolClassStudent> GetAllSchoolClassStudents(); 
        SchoolClassStudent GetSchoolClassStudent_SimpleByID(int? schoolClassStudentID); 
        SchoolClassStudent GetSchoolClassStudentByID(int? schoolClassStudentID); 

        SchoolClassStudent GetNewestSchoolClassStudent(); 
        void InsertSchoolClassStudent(SchoolClassStudent company, int schoolClassStudentID); 
        void DeleteSchoolClassStudent(int schoolClassStudentID); 
        void UpdateSchoolClassStudent(SchoolClassStudent company, int schoolClassStudentID); 
        void Save(); 


     } 
} 

