using System; 
using System.Data; 
using System.Data.Entity; 
using System.Collections.Generic; 
using yalms.Models; 

namespace yalms.DAL 
{ 
   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:38
   /// Object derived from the  User table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    public interface IUserRepository : IDisposable 
    {
        IEnumerable<DomainUser> GetAllUsers();
        DomainUser GetUser_SimpleByID(int? userID);
        DomainUser GetUserByID(int? userID);

        DomainUser GetNewestUser();
        void InsertUser(DomainUser company, int userID); 
        void DeleteUser(int userID);
        void UpdateUser(DomainUser company, int userID); 
        void Save(); 


     } 
} 

