 
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.Entity;
using System.Configuration;
using yalms.Models; 

namespace yalms.DAL
{

   /// <summary>
   /// ---------------------------------------------------------------------------------------------------
   /// File Autogenerated at 2016-03-16 23:23:38
   /// Object derived from the  Upload table in the LMSProject database.
   /// Solution version: 1.0.0.1
   /// [ ] Check box with 'x' to prevent entire file from being overwritten. 
   /// Do not move, remove or change the DMZ region markers. Code inside the DMZ will not be overwritten by auto generation.
   /// ---------------------------------------------------------------------------------------------------
   /// </summary>
    public class UploadRepository: IUploadRepository
    {
        // Get context for specific connectionstring.
        private EFContext context = new EFContext();



        #region Get all Uploads even those tagged as removed and not yet created.
        public IEnumerable<Upload> GetAllUploads()
        {
            return context.Uploads;
        }

        #endregion

        #region Get Upload by its Upload ID without populating foregin key data
        public Upload GetUpload_SimpleByID(int? uploadID)
        {
            // Get single Upload by its unique ID
            return context.Uploads.SingleOrDefault(o => o.UploadID == uploadID);

        }
        #endregion

        #region Get Upload by its Upload ID
        public Upload GetUploadByID(int? uploadID)
        {
            // Get single Upload by its unique ID
            var upload = context.Uploads.SingleOrDefault(o => o.UploadID == uploadID);


            return upload;
        }
        #endregion

        #region Get newest Upload.
        public Upload GetNewestUpload()
        {
           return context.Uploads.OrderByDescending(u => u.UploadID).FirstOrDefault();
        }
        #endregion

        #region Insert new Upload object and register what user created it and when.
        public void InsertUpload(Upload upload, int userID)
        {


            // Add Upload to context
            context.Uploads.Add(upload);

            // Save context changes.
            Save();
            Dispose();
        }
        #endregion

        #region Delete Upload  from database by Upload ID - Do not use unless sure it will not create data inconsistency and only if user is super Admin.
        public void DeleteUpload (int uploadID)
        {
            // Get Upload by ID.
            Upload upload = context.Uploads.SingleOrDefault(o => o.UploadID == uploadID);
            context.Uploads.Remove(upload);
        }
        #endregion

        #region Tag Upload as removed, and register what user removed it and when.
        public void RemoveUpload(Upload newUpload, int userID)
        {
            // Get Upload for update
            var oldUpload = context.Uploads.Single(o => o.UploadID == newUpload.UploadID);


            // Save context changes.
            Save();
            Dispose();
        }
        #endregion

        #region Update existing Upload object and register what user modified it and when.
        public void UpdateUpload (Upload newUpload,int userID)
        {
            // Get existing Upload object by ID for update.
            var oldUpload = context.Uploads.SingleOrDefault(o => o.UploadID == newUpload.UploadID);
            oldUpload.Description = newUpload.Description;
            oldUpload.Grade = newUpload.Grade;
            oldUpload.GradeDescription = newUpload.GradeDescription;
            oldUpload.Uploaded = newUpload.Uploaded;
            oldUpload.UploadedBy = newUpload.UploadedBy;



            // Save context changes.
            Save();
            Dispose();
        }
        #endregion

        #region Update Upload with foreignkey names for presentation.
        private Upload PopulateUploadWithForeignKeyDataObjects(Upload upload)
        {
            // Get objects for Sub keys
            upload.AssignmentID_Assignment = new AssignmentRepository().GetAssignment_SimpleByID(upload.AssignmentID);
            return upload;
        }
        #endregion



        #region System functions.
        public void Save()
        {
            context.SaveChanges();
        }

        private bool disposed = false;

        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                if (disposing)
                {
                    context.Dispose();
                }
            }
            this.disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
        }

        #endregion


    }
}

